@SYSTEM.RETURN.CODE
CALL !ADDS(@TTY, @ACCOUNT)
GET @ACCOUNT
GETLIST @ACCOUNT @AUTHORIZATION
GROUPSTORE @AUTHORIZATION
$COPYRIGHT = @FILE.NAME
$COPYRIGHT = @DATA.PENDING
$COPYRIGHT = @ACCOUNT
$COPYRIGHT = @HDBC

